services:
  wg-easy-tg-bot:
    build: .
    container_name: wg-easy-tg-bot
    restart: unless-stopped
    user: "0:0"
    privileged: true
    env_file:
      - .env
    environment:
      - DOCKER_HOST=unix:///docker.sock
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/docker.sock
    security_opt:
      - apparmor:unconfined
    networks:
      - wg-easy-network
    command: ["/bin/sh","-c","chmod 666 /docker.sock || true; python -m app.main"]

networks:
  wg-easy-network:
    driver: bridge
