services:
  wg-easy-tg-bot:
    build: .
    container_name: wg-easy-tg-bot
    restart: unless-stopped
    user: "0:0"
    privileged: true
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - wg-easy-network

networks:
  wg-easy-network:
    driver: bridge
